version: "3.9"
name: kanban
services:
  postgres:
    container_name: kanban-postgres-db
    restart: unless-stopped
    env_file:
      - .env
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: kanban
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  server:
    container_name: kanban-server
    env_file:
      - .env
    build:
      context: ./packages/server
      args:
        - DATABASE_URL=postgresql://user:pass@postgres:5432/kanban
    ports:
      - "3000:3000"
    entrypoint: ["./scripts/start-up.sh"]
    depends_on:
      postgres:
        condition: service_started

volumes:
  postgres_data:
