version: "3.9"
name: kanban
services:
  postgres:
    container_name: kanban-postgres-db
    restart: unless-stopped
    env_file:
      - .env
    image: postgres
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  server:
    container_name: kanban-server
    env_file:
      - .env
    build:
      context: ./packages/server
      args:
        - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5433/${DB_NAME}
        - SERVER_PORT=${SERVER_PORT}
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    entrypoint: ["./scripts/start-up.sh"]
    depends_on:
      postgres:
        condition: service_started

volumes:
  postgres_data:
